language: c++

before_install:
  - sudo apt-get install cmake
  - sudo apt-get install liblapacke-dev liblapacke
  - sudo apt-get install libopenblas-dev libopenblas-base
  - sudo apt-get install libgsl0-dev
  - sudo apt-get install libjsoncpp-dev
  - sudo apt-get install libhdf5-dev libhdf5-serial-dev
  - sudo apt-get install libarmadillo-dev
  - sudo apt-get install libsfml-dev
  - sudo apt-get install libfltk1.3-dev
  - sudo apt-get install libfftw3-dev
  - sudo apt-get install libgtest-dev
  - sudo apt-get install swig
  - git clone https://github.com/davidkleiven/VISA.git
  - cd VISA/
  - cmake .
  - make
  - sudo make install
  - cd ..

install:
  - cmake .
  - make
  - sudo make install
  - mkdir data

script:
  - ./waveguide2D.out
  - ./primitiveGeomExample.out
